language: python
cache:
  directories:
    - buildout-cache
python:
  - 2.7
sudo: false
env:
  - PLONE_VERSION=4.3 TEST_EGGS=collective.messageviewlet[plone4]
  - PLONE_VERSION=5.0 TEST_EGGS=collective.messageviewlet[plone5]
  - PLONE_VERSION=5.1 TEST_EGGS=collective.messageviewlet[plone5]

install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - sed -ie "s#travis-5.x#travis-$PLONE_VERSION#" travis.cfg
  - sed -ie "s#5-latest#$PLONE_VERSION#" buildout.cfg
  - python bootstrap-buildout.py --version=2.5.3 -c travis.cfg
  - bin/buildout -Nc travis.cfg buildout:test-eggs=$TEST_EGGS annotate
  - bin/buildout -Nc travis.cfg buildout:test-eggs=$TEST_EGGS

script:
  - bin/test
  - bin/createcoverage run bin/test

after_success:
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
    - devs@imio.be
