language: python

sudo: false

services:
  - xvfb

cache:
  directories:
    - eggs
    - downloads

python:
  - 2.7

env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.1

install:
  - sed -ie "s#5.1#$PLONE_VERSION#" buildout.cfg
  - python bootstrap-buildout.py --version=2.11.4
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True

before_script:
  - firefox -v

script:
  - bin/test

after_success:
  - bin/createcoverage --output-dir htmlcov
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
    - devs@imio.be
