language: python

sudo: false

services:
  - xvfb

cache:
  directories:
    - eggs
    - downloads

python:
  - 2.7

matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=4.3
    - python: "2.7"
      env: PLONE_VERSION=5.1
    - python: "2.7"
      env: PLONE_VERSION=5.2
    - python: "3.7"
      env: PLONE_VERSION=5.2
  sudo: true
  fast_finish: true

install:
  - sed -ie "s#5#$PLONE_VERSION#" buildout.cfg
  - pip install -r requirements.txt
  - python bootstrap-buildout.py
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True

before_script:
  - firefox -v

script:
  - bin/test

after_success:
  - bin/createcoverage --output-dir htmlcov
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
    - devs@imio.be
