language: python

python:
  - 2.7

install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap-buildout.py --version=2.5.3 -c travis.cfg
  - bin/buildout -Nc travis.cfg

script:
  - bin/test
  - bin/createcoverage run bin/test

after_success:
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
    - devs@imio.be
