language: python

python:
  - 2.7

cache:
  pip: true
  directories:
    - buildout-cache/downloads
    - buildout-cache/eggs

install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap-buildout.py --version=2.10.0 -c travis.cfg
  - bin/buildout -Nc travis.cfg

script:
  - bin/test
  - bin/coverage run bin/test

after_success:
  - bin/coverage run bin/test
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
    - devs@imio.be
