language: python
sudo: false
cache:
  directories:
    - eggs
    - downloads
python:
  - 2.7
env:
  - PLONE_VERSION=4.3 TEST_EGGS=collective.messagesviewlet [plone4]
  - PLONE_VERSION=5.0 TEST_EGGS=collective.messagesviewlet [plone5]
  - PLONE_VERSION=5.1 TEST_EGGS=collective.messagesviewlet [plone5]
install:
  - sed -ie "s#5-latest#$PLONE_VERSION-latest#" buildout.cfg
  - python bootstrap-buildout.py --version=2.5.3
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True buildout:test-eggs=$TEST_EGGS annotate
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True buildout:test-eggs=$TEST_EGGS
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script:
  - bin/test

after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
notifications:
  email:
    - devs@imio.be
